### ISSUE TITLE
Compatibility with Energy Management

### ISSUE THREAD

**Issue by Ganayan** [mchwalisz/home-assistant-senec#12]
Thank you so much for the Senec integration - this one works awesome!

I was wondering if there are plans to add the accumulated kWh values for to / from grid in order to feed it into Home Assistant's energy management dashboard. 

Is something like this planned?

**Comment by CinderXx** [comment]
+

**Comment by guevara777** [comment]
+1

**Comment by frittes** [comment]
You can realise that with the integration integration and the utility_meter in HA. Use sensor.senec_grid_imported_power and sensor.senec_grid_exported_power for it.

<img width="1623" alt="Bildschirmfoto 2021-09-19 um 19 28 34" src="https://user-images.githubusercontent.com/33233288/133936989-9d15fa6f-5e46-4231-8c29-d9f3804a74bd.png">

**Comment by klaus1956** [comment]
Using the data from this integration in energy management I face the issue that single peaks of high load ( e.g. El. hot water) create very high very false sum values.
As nobody in the general discussions observes the same: can this be a issue of this integration?

**Comment by h4nnes** [comment]
Hi @frittes,
can you please share your statistics entry for this?

**Comment by klaus1956** [comment]
Hello
My problem is still not solved - recording works, but load peaks still are massively overevaluated so that imported energy is often app. 3 times higher than real.

Here is my Sensor section from configuration.yaml
[senec-sensors.txt](https://github.com/mchwalisz/home-assistant-senec/files/7360602/senec-sensors.txt)

**Comment by frittes** [comment]
@klaus1956 Chose method: left in the utility_meter config.

For me, that solves the three times higher kWh, when the battery gets loaded from grid.

**Comment by CinderXx** [comment]
Hi, did you get the integration with the versions
supervisor-2021.10.0 and core-2021.10.6?
With 2021.9.7 it has recognized my sensors from the sensor.yaml but now no longer

**Comment by mchwalisz** [comment]
> Yes, I also have the SENEC.Home V3 hybrid duo.
> 
> > I have another question about the sensors. Does anyone have the "SENEC.Home V3 hybrid duo"? For this there seems to be no entities for battery discharge or battery charge. can anyone confirm this?
> 
> Like @frittes said, you have add two sensors in your /config/custom_components/senec/const.py
> 
> ` "battery_charge_power": [POWER_WATT, "mdi:battery-positive"],` ` "battery_discharge_power": [POWER_WATT, "mdi:battery-negative"],`

Patch with those is already on master. I'm trying to figure out how to implement integral sensor as part of the integration itself to simplify the setup.

**Comment by Shakarls** [comment]
> Short way to solve it:
> 
> 1. Create new **sensors**. See [Integration - Riemann sum integral](https://www.home-assistant.io/integrations/integration/)
>    Example:
> 
> ```
>   - platform: integration
>     source: sensor.senec_solar_generated_power
>     name: Stromproduktion
>     unit_prefix: k
>     unit_time: h
>     method: left
>     round: 2
> ```
> 
> 2. Customize **entities** (Settings > Customize entities). You have to set device_class "energy":
>    ![image](https://user-images.githubusercontent.com/76157868/138074756-0a9b85ed-914e-4cdb-8376-68eb1b1ff282.png)
> 3. Use the new sensors at **energy management**.
>    ![image](https://user-images.githubusercontent.com/76157868/138074572-98602a5d-51fa-4c0a-8751-49767a1dc12b.png)
> 
> Done.

I've tried this, but after the configuration I get the message that "This entity does not have a unique ID, therefore its settings cannot be managed from the UI" can anyone help?

**Comment by JoJa1101** [comment]
Try to use different names for your sensors and then delete the old ones. The sensor names have to be unique!

**Comment by Shakarls** [comment]
I have tried this now with different names, include restart, loading an old image an so on, but it wont work :/
here is the senor code

```
sensor:
  - platform: template
    sensors:
      battery_power_charge:
        unit_of_measurement: "W"
        value_template: >-
          {% if states('sensor.senec_battery_state_power')|float > 0 %}
            {{ states('sensor.senec_battery_state_power')|float | round(2) }}
          {% else %}
            0
          {% endif %}
      battery_power_discharge:
        unit_of_measurement: "W"
        value_template: >-
          {% if states('sensor.senec_battery_state_power')|float < 0 %}
            {{ (-1 * (states('sensor.senec_battery_state_power')|float)) | round(2) }}
          {% else %}
            0
          {% endif %}

  - platform: integration
    source: sensor.senec_solar_generated_power
    name: generierte_leistungdaily
    unit_prefix: k
    unit_time: h
    method: left
    round: 2
  - platform: integration
    source: sensor.senec_grid_exported_power
    name: abgegebene_leistungdaily
    unit_prefix: k
    unit_time: h
    method: left
    round: 2
  - platform: integration
    source: sensor.senec_house_power
    name: leistungsverbrauchdaily
    unit_prefix: k
    unit_time: h
    method: left
    round: 2
  - platform: integration
    source: sensor.senec_grid_imported_power
    name: netzbezugdaily
    unit_prefix: k
    unit_time: h
    method: left
    round: 2
  - platform: integration
    source: sensor.battery_power_charge
    name: batterieladungdaily
    unit_prefix: k
    unit_time: h
    unit: kWh
    round: 2
  - platform: integration
    source: sensor.battery_power_discharge
    name: batterieentladungdaily
    unit_prefix: k
    unit_time: h
    unit: kWh
    round: 2
```
